### ISSUE TITLE
Remove "immature" tools (post time coordination, graphing post time) from the cli for the MVP

### ISSUE THREAD

**Issue by sandytribal** [CIB-Mango-Tree/mango-tango-cli#44] opened 2024-12-13 00:44 UTC
Better the leave just copypasta on the cli for the Jan iteration since the other tools do not have clear outputs yet, and in the case of post time coordination, don't run too well as of yet

**Comment by soul-codes** [comment] 2024-12-13 01:07
Duplicate of #46

**Closed by soul-codes** 2024-12-13 01:07 UTC
Labels: duplicate
